// Country data for the international bot doctors (one female + one male per
// specialty per country). Names, cities and hospitals are plausible public
// institutions; the doctors themselves are fictional.

export const WORLD = {
  MY: { city: "Kuala Lumpur", lat: 3.139, lng: 101.6869,
    hospitals: ["Hospital Kuala Lumpur", "University Malaya Medical Centre", "Sunway Medical Centre", "Prince Court Medical Centre"],
    schools: ["Universiti Malaya", "UKM", "Monash Malaysia", "IMU"],
    female: ["Nur Aisyah", "Siti Hajar", "Mei Ling", "Priya", "Farah", "Hui Min", "Amira", "Kavitha"],
    male: ["Ahmad Faiz", "Hafiz", "Wei Jie", "Arjun", "Iskandar", "Jun Hao", "Amirul", "Ravi"],
    last: ["Abdullah", "Ismail", "Tan", "Lim", "Rahman", "Wong", "Nair", "Hashim"] },
  SG: { city: "Singapore", lat: 1.3521, lng: 103.8198,
    hospitals: ["Singapore General Hospital", "National University Hospital", "Tan Tock Seng Hospital", "Mount Elizabeth Hospital"],
    schools: ["NUS Yong Loo Lin", "Duke-NUS", "NTU Lee Kong Chian"],
    female: ["Rachel", "Shu Fen", "Nadia", "Grace", "Xin Yi", "Deepa", "Hui Shan", "Clara"],
    male: ["Marcus", "Wei Ming", "Daniel", "Shawn", "Hafiz", "Jun Wei", "Ryan", "Kumar"],
    last: ["Tan", "Lim", "Ng", "Lee", "Goh", "Chua", "Pillai", "Koh"] },
  BN: { city: "Bandar Seri Begawan", lat: 4.9031, lng: 114.9398,
    hospitals: ["RIPAS Hospital", "Jerudong Park Medical Centre", "Gleneagles JPMC"],
    schools: ["Universiti Brunei Darussalam", "PAPRSB Institute of Health Sciences"],
    female: ["Nurul", "Siti Aminah", "Dayangku", "Hajah Noor", "Afiqah", "Syazwani", "Aqilah", "Rafidah"],
    male: ["Awang", "Haji Hamzah", "Pengiran Amin", "Khairul", "Azri", "Hazwan", "Syafiq", "Rizal"],
    last: ["Abdullah", "Hamid", "Yusof", "Bakar", "Salleh", "Ali", "Jaafar", "Osman"] },
  TH: { city: "Bangkok", lat: 13.7563, lng: 100.5018,
    hospitals: ["Siriraj Hospital", "King Chulalongkorn Memorial Hospital", "Ramathibodi Hospital", "Bumrungrad International"],
    schools: ["Mahidol University", "Chulalongkorn University", "Chiang Mai University"],
    female: ["Ploy", "Nattaya", "Siriporn", "Kanya", "Pimchanok", "Malee", "Achara", "Waraporn"],
    male: ["Somchai", "Thanakorn", "Nattapong", "Krit", "Anan", "Pichit", "Sakda", "Teerapat"],
    last: ["Srisuk", "Wongsakul", "Chaiyaporn", "Rattanakul", "Saetang", "Boonmee", "Phromma", "Kittisak"] },
  PH: { city: "Manila", lat: 14.5995, lng: 120.9842,
    hospitals: ["Philippine General Hospital", "St. Luke's Medical Center", "The Medical City", "Makati Medical Center"],
    schools: ["UP College of Medicine", "UST Faculty of Medicine", "Ateneo SMPH"],
    female: ["Maria Clara", "Andrea", "Kristine", "Patricia", "Bea", "Joanna", "Camille", "Liza"],
    male: ["Juan Carlos", "Miguel", "Paolo", "Rafael", "Joshua", "Marco", "Gabriel", "Enzo"],
    last: ["Santos", "Reyes", "Cruz", "Bautista", "Garcia", "Mendoza", "Villanueva", "Dela Cruz"] },
  VN: { city: "Ho Chi Minh City", lat: 10.8231, lng: 106.6297,
    hospitals: ["Cho Ray Hospital", "Bach Mai Hospital", "Vinmec Central Park", "FV Hospital"],
    schools: ["Hanoi Medical University", "UMP Ho Chi Minh City", "Pham Ngoc Thach University"],
    female: ["Linh", "Mai", "Thao", "Huong", "Trang", "Ngoc Anh", "Lan", "Phuong"],
    male: ["Minh", "Duc", "Tuan", "Hoang", "Quang", "Khoa", "Long", "Bao"],
    last: ["Nguyen", "Tran", "Le", "Pham", "Hoang", "Vu", "Dang", "Bui"] },
  KH: { city: "Phnom Penh", lat: 11.5564, lng: 104.9282,
    hospitals: ["Calmette Hospital", "Royal Phnom Penh Hospital", "Khmer-Soviet Friendship Hospital"],
    schools: ["University of Health Sciences Cambodia", "International University Phnom Penh"],
    female: ["Sreymom", "Chanthy", "Sophea", "Bopha", "Dara", "Sokha", "Rachana", "Kalyan"],
    male: ["Sokha", "Vannak", "Rithy", "Dara", "Piseth", "Sovann", "Chanthol", "Visal"],
    last: ["Chan", "Sok", "Heng", "Kim", "Ly", "Meas", "Pich", "Seng"] },
  MM: { city: "Yangon", lat: 16.8409, lng: 96.1735,
    hospitals: ["Yangon General Hospital", "Pun Hlaing Hospital", "Asia Royal Hospital"],
    schools: ["University of Medicine 1 Yangon", "University of Medicine Mandalay"],
    female: ["Thandar", "Su Su", "Hnin Wai", "Nwe Ni", "May Thu", "Khin Lay", "Ei Mon", "Zar Chi"],
    male: ["Aung Ko", "Min Thu", "Kyaw Zin", "Htet Naing", "Zaw Win", "Thura", "Naing Lin", "Ye Htut"],
    last: ["Win", "Oo", "Aung", "Htun", "Myint", "Soe", "Kyaw", "Lwin"] },
  LA: { city: "Vientiane", lat: 17.9757, lng: 102.6331,
    hospitals: ["Mahosot Hospital", "Setthathirath Hospital", "Mittaphab Hospital"],
    schools: ["University of Health Sciences Laos"],
    female: ["Noy", "Phonesavanh", "Khamla", "Vilayvanh", "Manivone", "Souksavanh", "Bouasone", "Chanthala"],
    male: ["Somsack", "Khampheng", "Souliya", "Bounmy", "Phouvong", "Anousone", "Vongsa", "Kham"],
    last: ["Phommasack", "Sengdara", "Keomany", "Vongsavath", "Sisouk", "Inthavong", "Chanthavong", "Siharath"] },
  TL: { city: "Dili", lat: -8.5569, lng: 125.5603,
    hospitals: ["Hospital Nacional Guido Valadares", "Bairo Pite Clinic"],
    schools: ["Universidade Nacional Timor Lorosa'e"],
    female: ["Maria", "Ana", "Lucia", "Joana", "Filomena", "Rosa", "Teresa", "Isabel"],
    male: ["Jose", "Antonio", "Manuel", "Joao", "Francisco", "Mario", "Lucas", "Tomas"],
    last: ["da Silva", "Soares", "Pereira", "Guterres", "Ximenes", "Belo", "Amaral", "Freitas"] },
  AU: { city: "Sydney", lat: -33.8688, lng: 151.2093,
    hospitals: ["Royal Prince Alfred Hospital", "St Vincent's Hospital Sydney", "Westmead Hospital", "Royal North Shore Hospital"],
    schools: ["University of Sydney", "UNSW", "Monash University", "University of Melbourne"],
    female: ["Charlotte", "Olivia", "Isla", "Chloe", "Matilda", "Grace", "Zoe", "Harper"],
    male: ["Jack", "Liam", "Oliver", "Noah", "Lachlan", "Cooper", "Ethan", "Hamish"],
    last: ["Smith", "Wilson", "Taylor", "Brown", "Nguyen", "Campbell", "O'Brien", "Kelly"] },
  NZ: { city: "Auckland", lat: -36.8485, lng: 174.7633,
    hospitals: ["Auckland City Hospital", "Middlemore Hospital", "North Shore Hospital"],
    schools: ["University of Auckland", "University of Otago"],
    female: ["Aroha", "Mia", "Ruby", "Ngaio", "Sophie", "Georgia", "Kaia", "Lucy"],
    male: ["Tane", "Oliver", "Mason", "Nikau", "Leo", "Finn", "Hunter", "Wiremu"],
    last: ["Smith", "Williams", "Ngata", "Parata", "Wilson", "Thompson", "Walker", "Tipene"] },
  JP: { city: "Tokyo", lat: 35.6762, lng: 139.6503,
    hospitals: ["University of Tokyo Hospital", "St. Luke's International Hospital", "Keio University Hospital", "Toranomon Hospital"],
    schools: ["University of Tokyo", "Kyoto University", "Keio University", "Osaka University"],
    female: ["Yui", "Haruka", "Sakura", "Aoi", "Mei", "Rina", "Yuna", "Misaki"],
    male: ["Haruto", "Ren", "Sota", "Yuto", "Kaito", "Takumi", "Riku", "Daiki"],
    last: ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura"] },
  KR: { city: "Seoul", lat: 37.5665, lng: 126.978,
    hospitals: ["Seoul National University Hospital", "Samsung Medical Center", "Asan Medical Center", "Severance Hospital"],
    schools: ["Seoul National University", "Yonsei University", "Korea University"],
    female: ["Ji-woo", "Seo-yeon", "Min-ji", "Ha-eun", "Soo-ah", "Ye-jin", "Da-eun", "Yu-na"],
    male: ["Min-jun", "Seo-jun", "Do-yoon", "Ji-ho", "Hyun-woo", "Joon-young", "Tae-yang", "Sung-min"],
    last: ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon"] },
  CN: { city: "Shanghai", lat: 31.2304, lng: 121.4737,
    hospitals: ["Ruijin Hospital", "Huashan Hospital", "Zhongshan Hospital", "Peking Union Medical College Hospital"],
    schools: ["Fudan University", "Peking Union Medical College", "Shanghai Jiao Tong University"],
    female: ["Xiaoyu", "Mengqi", "Yuxin", "Jiayi", "Shuting", "Wenjing", "Ruoxi", "Lingling"],
    male: ["Haoran", "Zihan", "Yuchen", "Junjie", "Tianyu", "Zhiwei", "Bowen", "Hao"],
    last: ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Zhao", "Huang"] },
  TW: { city: "Taipei", lat: 25.033, lng: 121.5654,
    hospitals: ["National Taiwan University Hospital", "Taipei Veterans General Hospital", "Mackay Memorial Hospital"],
    schools: ["National Taiwan University", "National Yang Ming Chiao Tung University", "Taipei Medical University"],
    female: ["Yi-Ting", "Hsin-Yi", "Pei-Shan", "Ya-Wen", "Chia-Hui", "Shu-Hua", "Wan-Ting", "Hui-Chen"],
    male: ["Chih-Wei", "Yu-Hsiang", "Cheng-Han", "Po-Yu", "Tsung-Han", "Chun-Hao", "Wei-Lun", "Kuan-Ting"],
    last: ["Chen", "Lin", "Huang", "Chang", "Lee", "Wang", "Wu", "Tsai"] },
  HK: { city: "Hong Kong", lat: 22.3193, lng: 114.1694,
    hospitals: ["Queen Mary Hospital", "Prince of Wales Hospital", "Hong Kong Sanatorium & Hospital"],
    schools: ["HKU Li Ka Shing", "CUHK Faculty of Medicine"],
    female: ["Cheryl", "Hoi Yan", "Vivian", "Wing Sze", "Karen", "Ka Man", "Tiffany", "Sum Yi"],
    male: ["Kelvin", "Ka Ho", "Jason", "Chun Kit", "Edmond", "Wai Lun", "Raymond", "Tsz Hin"],
    last: ["Chan", "Wong", "Leung", "Cheung", "Lau", "Ho", "Ng", "Lam"] },
  IN: { city: "Mumbai", lat: 19.076, lng: 72.8777,
    hospitals: ["AIIMS New Delhi", "Tata Memorial Hospital", "KEM Hospital Mumbai", "Lilavati Hospital"],
    schools: ["AIIMS", "CMC Vellore", "Seth GSMC", "Maulana Azad Medical College"],
    female: ["Ananya", "Priya", "Aditi", "Kavya", "Sneha", "Meera", "Isha", "Riya"],
    male: ["Arjun", "Rohan", "Vikram", "Aditya", "Karthik", "Rahul", "Siddharth", "Aman"],
    last: ["Sharma", "Patel", "Iyer", "Reddy", "Gupta", "Nair", "Menon", "Desai"] },
  PK: { city: "Lahore", lat: 31.5204, lng: 74.3587,
    hospitals: ["Mayo Hospital Lahore", "Aga Khan University Hospital", "Shaukat Khanum Memorial Hospital"],
    schools: ["King Edward Medical University", "Aga Khan University", "Dow University"],
    female: ["Ayesha", "Fatima", "Hira", "Mahnoor", "Zainab", "Sana", "Iqra", "Amna"],
    male: ["Ali", "Hamza", "Usman", "Bilal", "Saad", "Ahmed", "Hassan", "Faraz"],
    last: ["Khan", "Ahmed", "Malik", "Qureshi", "Butt", "Chaudhry", "Siddiqui", "Raza"] },
  BD: { city: "Dhaka", lat: 23.8103, lng: 90.4125,
    hospitals: ["Dhaka Medical College Hospital", "Square Hospital", "BSMMU Hospital", "Evercare Dhaka"],
    schools: ["Dhaka Medical College", "Sir Salimullah Medical College", "BSMMU"],
    female: ["Nusrat", "Tasnim", "Farhana", "Sadia", "Rumana", "Mithila", "Anika", "Lamia"],
    male: ["Rakib", "Tanvir", "Arif", "Shahriar", "Fahim", "Imran", "Mahmud", "Nafis"],
    last: ["Rahman", "Hossain", "Islam", "Ahmed", "Chowdhury", "Uddin", "Haque", "Karim"] },
  LK: { city: "Colombo", lat: 6.9271, lng: 79.8612,
    hospitals: ["National Hospital of Sri Lanka", "Lady Ridgeway Hospital", "Nawaloka Hospital"],
    schools: ["University of Colombo", "University of Peradeniya", "University of Kelaniya"],
    female: ["Nimali", "Tharushi", "Dilini", "Sanduni", "Kavindi", "Ishara", "Hiruni", "Shehani"],
    male: ["Kasun", "Nuwan", "Tharindu", "Chamara", "Dinesh", "Lahiru", "Sahan", "Pasindu"],
    last: ["Perera", "Fernando", "Silva", "Jayasinghe", "Wickramasinghe", "Bandara", "Dissanayake", "Gunawardena"] },
  SA: { city: "Riyadh", lat: 24.7136, lng: 46.6753,
    hospitals: ["King Faisal Specialist Hospital", "King Fahad Medical City", "King Khalid University Hospital"],
    schools: ["King Saud University", "King Abdulaziz University", "Alfaisal University"],
    female: ["Noura", "Reem", "Lama", "Sara", "Haya", "Dana", "Raghad", "Joud"],
    male: ["Abdullah", "Faisal", "Khalid", "Saud", "Turki", "Omar", "Nawaf", "Fahad"],
    last: ["Al-Saud", "Al-Otaibi", "Al-Qahtani", "Al-Harbi", "Al-Ghamdi", "Al-Shehri", "Al-Dossari", "Al-Mutairi"] },
  AE: { city: "Dubai", lat: 25.2048, lng: 55.2708,
    hospitals: ["Rashid Hospital", "Cleveland Clinic Abu Dhabi", "Mediclinic City Hospital", "American Hospital Dubai"],
    schools: ["MBRU", "UAE University", "Gulf Medical University"],
    female: ["Mariam", "Fatima", "Shamma", "Alia", "Hessa", "Latifa", "Noor", "Maitha"],
    male: ["Rashid", "Hamdan", "Saeed", "Mohammed", "Sultan", "Khalifa", "Ahmed", "Majid"],
    last: ["Al Maktoum", "Al Nahyan", "Al Falasi", "Al Mazrouei", "Al Suwaidi", "Al Shamsi", "Al Ketbi", "Al Hammadi"] },
  QA: { city: "Doha", lat: 25.2854, lng: 51.531,
    hospitals: ["Hamad General Hospital", "Sidra Medicine", "Al Wakra Hospital"],
    schools: ["Weill Cornell Medicine Qatar", "Qatar University College of Medicine"],
    female: ["Aisha", "Maryam", "Noof", "Hind", "Asma", "Latifa", "Sheikha", "Moza"],
    male: ["Tamim", "Jassim", "Hamad", "Nasser", "Abdulrahman", "Mohammed", "Khalid", "Ali"],
    last: ["Al Thani", "Al Kuwari", "Al Marri", "Al Sulaiti", "Al Naimi", "Al Hajri", "Al Mannai", "Al Khater"] },
  EG: { city: "Cairo", lat: 30.0444, lng: 31.2357,
    hospitals: ["Kasr Al Ainy Hospital", "Ain Shams University Hospital", "Dar Al Fouad Hospital"],
    schools: ["Cairo University", "Ain Shams University", "Alexandria University"],
    female: ["Nour", "Mariam", "Salma", "Yasmin", "Habiba", "Farida", "Rana", "Dina"],
    male: ["Omar", "Youssef", "Ahmed", "Karim", "Mostafa", "Ziad", "Hassan", "Amr"],
    last: ["Hassan", "Mahmoud", "Ibrahim", "El-Sayed", "Abdelrahman", "Fawzy", "Gamal", "Mansour"] },
  TR: { city: "Istanbul", lat: 41.0082, lng: 28.9784,
    hospitals: ["Istanbul University Cerrahpasa", "Acibadem Maslak Hospital", "Koc University Hospital"],
    schools: ["Hacettepe University", "Istanbul University", "Ankara University"],
    female: ["Zeynep", "Elif", "Defne", "Ece", "Ayse", "Selin", "Buse", "Irem"],
    male: ["Emre", "Mehmet", "Can", "Burak", "Kerem", "Ahmet", "Mert", "Arda"],
    last: ["Yilmaz", "Kaya", "Demir", "Sahin", "Celik", "Yildiz", "Aydin", "Ozturk"] },
  NL: { city: "Amsterdam", lat: 52.3676, lng: 4.9041,
    hospitals: ["Amsterdam UMC", "Erasmus MC", "UMC Utrecht", "LUMC"],
    schools: ["University of Amsterdam", "Erasmus University", "Leiden University"],
    female: ["Sanne", "Lotte", "Fleur", "Emma", "Anouk", "Julia", "Iris", "Femke"],
    male: ["Daan", "Bram", "Thijs", "Lars", "Sem", "Ruben", "Joost", "Pieter"],
    last: ["de Jong", "Jansen", "de Vries", "van Dijk", "Bakker", "Visser", "Smit", "Meijer"] },
  DE: { city: "Berlin", lat: 52.52, lng: 13.405,
    hospitals: ["Charite Berlin", "LMU Klinikum Munich", "Heidelberg University Hospital", "UKE Hamburg"],
    schools: ["Charite", "LMU Munich", "Heidelberg University"],
    female: ["Lena", "Hannah", "Lea", "Johanna", "Marie", "Katharina", "Anna", "Laura"],
    male: ["Lukas", "Felix", "Jonas", "Maximilian", "Leon", "Paul", "Tobias", "Niklas"],
    last: ["Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Wagner", "Becker", "Hoffmann"] },
  GB: { city: "London", lat: 51.5074, lng: -0.1278,
    hospitals: ["St Thomas' Hospital", "Royal London Hospital", "John Radcliffe Hospital", "Addenbrooke's Hospital"],
    schools: ["Imperial College London", "UCL", "University of Oxford", "University of Cambridge"],
    female: ["Amelia", "Isla", "Eleanor", "Poppy", "Freya", "Imogen", "Harriet", "Alice"],
    male: ["Oliver", "George", "Harry", "Arthur", "Theo", "Alfie", "Freddie", "Rory"],
    last: ["Smith", "Jones", "Williams", "Taylor", "Davies", "Evans", "Patel", "Hughes"] },
  FR: { city: "Paris", lat: 48.8566, lng: 2.3522,
    hospitals: ["Hopital Pitie-Salpetriere", "Hopital Necker", "Hopital Europeen Georges-Pompidou"],
    schools: ["Sorbonne Universite", "Universite Paris Cite", "Universite de Lyon"],
    female: ["Camille", "Chloe", "Manon", "Lea", "Ines", "Juliette", "Margaux", "Elise"],
    male: ["Louis", "Hugo", "Gabriel", "Arthur", "Lucas", "Theo", "Antoine", "Mathis"],
    last: ["Martin", "Bernard", "Dubois", "Moreau", "Laurent", "Lefebvre", "Girard", "Rousseau"] },
  IE: { city: "Dublin", lat: 53.3498, lng: -6.2603,
    hospitals: ["St James's Hospital", "Beaumont Hospital", "Mater Misericordiae University Hospital"],
    schools: ["Trinity College Dublin", "RCSI", "University College Dublin"],
    female: ["Aoife", "Saoirse", "Niamh", "Ciara", "Roisin", "Orla", "Siobhan", "Clodagh"],
    male: ["Cian", "Oisin", "Darragh", "Eoin", "Padraig", "Conor", "Fionn", "Ronan"],
    last: ["Murphy", "Kelly", "O'Sullivan", "Walsh", "O'Brien", "Byrne", "Ryan", "O'Connor"] },
  US: { city: "New York", lat: 40.7128, lng: -74.006,
    hospitals: ["NewYork-Presbyterian", "Mount Sinai Hospital", "NYU Langone", "Massachusetts General Hospital"],
    schools: ["Johns Hopkins", "Harvard Medical School", "Columbia University", "Stanford Medicine"],
    female: ["Emily", "Madison", "Ashley", "Sarah", "Jessica", "Hannah", "Megan", "Lauren"],
    male: ["Michael", "Tyler", "Brandon", "Ryan", "Matthew", "Justin", "Andrew", "Kevin"],
    last: ["Johnson", "Miller", "Davis", "Garcia", "Rodriguez", "Martinez", "Anderson", "Thompson"] },
  CA: { city: "Toronto", lat: 43.6532, lng: -79.3832,
    hospitals: ["Toronto General Hospital", "Sunnybrook Health Sciences Centre", "St. Michael's Hospital", "Mount Sinai Toronto"],
    schools: ["University of Toronto", "McGill University", "UBC", "McMaster University"],
    female: ["Ava", "Sophie", "Maya", "Chloe", "Leah", "Abigail", "Nora", "Mackenzie"],
    male: ["Liam", "Lucas", "Owen", "Nathan", "Logan", "Benjamin", "Caleb", "Dylan"],
    last: ["Tremblay", "Roy", "MacDonald", "Wilson", "Chen", "Singh", "Campbell", "Gagnon"] },
};
